dist: xenial
language: php
services:
  - docker
php:
- 7.2
- 7.3
env:
  global:
  - WP_VERSION=latest WP_MULTISITE=0
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
cache:
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
install:
- nvm install 12
- npm install
- npm rebuild node-sass
- composer install
- npm run build
script:
- npm run test
before_deploy:
- npm run zip
- ls -la snow-monkey-dropdown-navigation.zip
- export RELEASE_FILE=$(ls snow-monkey-dropdown-navigation.zip)
deploy:
deploy:
  provider: releases
  api_key:
    secure: ClZXnJ+49qIMvCulQvOCPBCTN4FurZAAFghvS+jL93ACPtmtpgolpG5TcKxS1+EvHf8cvgEuLrRC49L613Pga//WyZzXpD0XrgxQBknw/m+9GpzpvWoPWOq8+Wy7roQ4AKXXT2JZmUlrjajBpUTjxqPLW+SsEL2M8YNg8HgaXp3vjICvffxjwcuyCzVSmNnT6ZfNkIRd8f8b3aBPpjNdLTpY4587EtoxR3JyHaDYUAuiqW9RYJDjZjk5rYpc20w+wGsVIjhi+CiKO52PUk9lKbkkOTBOuLtjjBNi6ZZslLbLLh+Fd8V0zPsRfXNuUWYNrqH5hdU0dP5vUc2XgiKeiEk7s+DyHoa47JPGTdkaYFopTEtqXIw+IrrzaZKMPBgKNZUBgkC/XIKREXz9w8K9pixV3TwT+Kpeb2D7b/YZCZwFl9+XZRnW/2DL+aqMCIvieP3lqHoOWyEAd7nHyYq8iJrHGdlJh2YckxTkr8+eMLHCnF3JyLQ77VI47XU3g4XMwaGkxXDrYft9bcC47JVmEqyJOPDx/Y7i3YOCAvKXLBqKa2r6UBsG7jC3RJlDc8dHMvyDsJKy/9wlCF9du0fS57lyjup1Zp/t0pDluCHcSI8hlLZZqEA6CxFUTvN2IhM2zhcvvklotYGtDoKO7JHQjFR8hflFAzeHVdmIx+XloUo=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    php: 7.3
    repo: inc2734/snow-monkey-dropdown-navigation
